language: node_js
node_js:
  - 7
cache: yarn
before_script:
  - yarn install
script:
  - yarn test
before_deploy:
  - yarn run build
after_success:
  - cat __coverage__/lcov.info | ./node_modules/.bin/coveralls
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master